source/ProjetGestionEval/ProjetGestionEval/Controllers/CollaborateurController.cs
using ProjetGestionEval;
using ProjetGestionEval.Models;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Net;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MySql.AspNet.Identity;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Owin;
using MySql.Data.MySqlClient;

namespace ProjetGestionEval.Controllers
{
    public class CollaborateurController : Controller
    {
        static string ConnectionString = "database=bd_gestion;server=localhost;uid=root";
        MySqlConnection Connection = new MySqlConnection(ConnectionString);
        private ApplicationUserManager _userManager;
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
        private async Task SignInAsync(ApplicationUser user, bool isPersistent)
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
            AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = isPersistent }, await user.GenerateUserIdentityAsync(UserManager));
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        bd_gestionEntities bd = new bd_gestionEntities();
        // GET: Collaborateur
        public ActionResult Index()
        {
            return View(bd.collaborateur.ToList());
        }

        // GET: Collaborateur/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.Evaluateur = bd.collaborateur.Where(m => m.IDCOLLABORATEUR == id).FirstOrDefault().FLAGEVAL;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            collaborateur CollT = bd.collaborateur.Find(id);
            if (CollT == null)
            {
                return HttpNotFound();
            }
            return View(CollT);
        }

        // GET: Collaborateur/Create
        public ActionResult Create()
        {
            ViewBag.IDFONCTION = new SelectList(bd.fonction, "IDFONCTION", "NOMFONCTION");
            return View();
        }

        // POST: Collaborateur/Create
        [HttpPost]
        public async Task<ActionResult> Create([Bind(Exclude = "IdUser")]RegisterViewModel model)
        {
            ViewBag.IDFONCTION = new SelectList(bd.fonction, "IDFONCTION", "NOMFONCTION");
            if (model.TYPECOLLABORATEUR == "P.E" || model.TYPECOLLABORATEUR == "Freelance")
                model.FLAGEVAL = false;
            try
            {
                // Convertir l'image
                if (model.File.ContentLength > (2 * 1024 * 1024))
                {
                    ModelState.AddModelError("CustomError", "File est plus 2mb");
                    return View();
                }
                if (!(model.File.ContentType == "image/jpeg" || model.File.ContentType == "image/gif"))
                {
                    ModelState.AddModelError("CustomError", "File alloued for jpeg and gif");
                    return View();

                }
                byte[] data = new byte[model.File.ContentLength];
                model.File.InputStream.Read(data, 0, model.File.ContentLength);
                model.IMAGE = data;
                //formulaire methode poste

                    var user = new ApplicationUser() { UserName = model.Email, Email = model.Email };
                    var resulte = await UserManager.CreateAsync(user,model.Password);
                        //await UserManager.CreateAsync(user, model.Password);

                    var userToInsert = bd.aspnetusers.Where(i => i.UserName == user.UserName).FirstOrDefault();
                    if (userToInsert != null)
                    {

                        var CollT = new collaborateur() { IdUser = userToInsert.Id, NOM = model.NOM, PRENOM = model.PRENOM, IDFONCTION = model.IDFONCTION, IMAGE = model.IMAGE, FLAGEVAL = model.FLAGEVAL,DATEEMBAUCHE=model.DATEEMBAUCHE,DATESORTIE=model.DATESORTIE,TYPECOLLABORATEUR=model.TYPECOLLABORATEUR };
                        var aspuser = bd.aspnetusers.Find(CollT.IdUser);
                        CollT.aspnetusers = aspuser;
                        var fonc = bd.fonction.Find(model.IDFONCTION);
                        CollT.fonction = fonc;
                        if (resulte.Succeeded)
                        {
                            var currentUser = UserManager.FindByName(user.UserName);
                            if (model.TYPECOLLABORATEUR == "Titulaire" || model.TYPECOLLABORATEUR == "Freelance")
                            {
                                if (model.FLAGEVAL == true)
                                {
                                    if (model.Email == "admin@admin.com" || model.Email == "admin@gmail.com")
                                    {
                                        var roleresult = UserManager.AddToRole(currentUser.Id, "admin");
                                    }
                                    else { var roleresult = UserManager.AddToRole(currentUser.Id, "superuser"); }
                                }
                                else { var roleresult = UserManager.AddToRole(currentUser.Id, "viewt"); }
                                //await SignInAsync(user, isPersistent: false);
                            }
                            else if (model.TYPECOLLABORATEUR == "P.E")
                            {
                                var roleresult = UserManager.AddToRole(currentUser.Id, "viewpe");
                            }

                            bd.collaborateur.Add(CollT);
                            bd.SaveChanges();
                            if (CollT.TYPECOLLABORATEUR == "P.E") { return RedirectToAction("Index", "CollaborateurPE"); }
                            else
                            {

                                return RedirectToAction("Index");
                            }
                        }
                        else {
                           
                            ViewBag.Err=resulte.Errors.ToString();                            
                        }
                    }

                
                else if (!ModelState.IsValid)
                {

                    return View();
                }

            }
            catch (Exception ex)
            {
                ViewBag.IDFONCTION = new SelectList(bd.fonction, "IDFONCTION", "NOMFONCTION");
                string tst = ex.Message;
                return View();
            }

            return View();
        }
        public ActionResult EditImage(int? id) {
            var coll = bd.collaborateur.Find(id);
            ViewBag.idcol = coll.IDCOLLABORATEUR;
            ViewBag.im=coll.IMAGE;
           
            return View();
        }
        [HttpPost]
        public ActionResult EditImage(int? id,[Bind(Include = "File")]RegisterViewModel model)
        {
            var coll = bd.collaborateur.Find(id);
            
            try {
                if(model.File!=null){
                if (model.File.ContentLength > (2 * 1024 * 1024))
                {
                    ModelState.AddModelError("CustomError", "File est plus 2mb");
                    return View();
                }
                if (!(model.File.ContentType == "image/jpeg" || model.File.ContentType == "image/gif"))
                {
                    ModelState.AddModelError("CustomError", "File alloued for jpeg and gif");
                    return View();

                }
                byte[] data = new byte[model.File.ContentLength];
                model.File.InputStream.Read(data, 0, model.File.ContentLength);
                model.IMAGE = data;
                coll.IMAGE = model.IMAGE;
                    }
                //if (ModelState.IsValid)
                //{
                    bd.Entry(coll).State = System.Data.Entity.EntityState.Modified;

                    

                    bd.SaveChanges();

                    
                        return RedirectToAction("Accueil","Home");
                    

                //}
                
            
            
            
            }
            catch { }

            return View();
        }

        // GET: Collaborateur/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.IDFONCTION = new SelectList(bd.fonction, "IDFONCTION", "NOMFONCTION", bd.collaborateur.Find(id).fonction.IDFONCTION);
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            collaborateur CollT = bd.collaborateur.Find(id);
            aspnetusers asp = bd.aspnetusers.Find(CollT.IdUser);
            if (CollT == null)
                return HttpNotFound();
            return View(CollT);
        }

        // POST: Collaborateur/Edit/5
        [HttpPost]
        public ActionResult Edit( collaborateur CollT)
        {
            int id = CollT.IDCOLLABORATEUR;
            ViewBag.IDFONCTION = new SelectList(bd.fonction, "IDFONCTION", "NOMFONCTION");
            collaborateur col = bd.collaborateur.Find(id);
            aspnetusers ass = bd.aspnetusers.Find(col.IdUser);

            col.NOM = CollT.NOM;
            col.PRENOM = CollT.PRENOM;
            col.DATEEMBAUCHE = CollT.DATEEMBAUCHE;
            col.DATESORTIE = CollT.DATESORTIE;
            col.TYPECOLLABORATEUR = CollT.TYPECOLLABORATEUR;
            col.FLAGEVAL = CollT.FLAGEVAL;
            col.IDFONCTION = CollT.IDFONCTION;

source/ProjetGestionEval/ProjetGestionEval/Views/Collaborateur/Details.cshtml
@model ProjetGestionEval.collaborateur

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}

<ul class="page-breadcrumb breadcrumb">
    <li>

        <a href="~/Home/Accueil">Acceuil</a>
        <i class="fa fa-circle"></i>
        <a href="~/Collaborateur/Index">Liste des Collaborateurs</a>
        <i class="fa fa-circle"></i>
        <a href="~/Collaborateur/Details/@Model.IDCOLLABORATEUR">Details</a>
        <i class="fa fa-circle"></i>
    </li>

</ul>

<div class="row">
    <div class="col-md-12">


        <!-- BEGIN PROFILE SIDEBAR -->
        <!-- PORTLET MAIN -->
        <center>
            <div class="col-md-12">
                <div class="portlet light col-md-offset-2 col-md-6">
                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">
                        <img src="data:image/png;base64,@Convert.ToBase64String(Model.IMAGE, 0,Model.IMAGE.Length)" class="img-responsive" />
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">

                        <div class="profile-usertitle-name">

                            @Html.DisplayFor(model => model.NOM)
                            @Html.DisplayFor(model => model.PRENOM)

                        </div>
                        <div class="profile-usertitle-job">
                            @Html.DisplayFor(model => model.aspnetusers.Email)
                        </div>

                        <div class="profile-usertitle-job">
                            @Html.DisplayFor(model => model.fonction.NOMFONCTION)
                        </div>
                        <div class="profile-usertitle-job">
                            @Html.DisplayFor(model => model.TYPECOLLABORATEUR)
                        </div>
                        <div class="profile-usertitle-job">
                            Embaucher le @Html.DisplayFor(modelItem => Model.DATEEMBAUCHE.Day)/@Html.DisplayFor(modelItem => Model.DATEEMBAUCHE.Month)/@Html.DisplayFor(modelItem => Model.DATEEMBAUCHE.Year)
                        </div>
                        <div class="profile-usertitle-job">
                            @{if(Model.DATESORTIE==null){
                             <div>   </div>
                              }else{
                                var xx = @Html.DisplayFor(model => model.DATESORTIE.Value.Day) + "/" + @Html.DisplayFor(model => model.DATESORTIE.Value.Month) + "/" + @Html.DisplayFor(model => model.DATESORTIE.Value.Year);
                                <div>Sortie le </div>@xx
                              }}

                        </div>
                        <div class="profile-usertitle-job">
                            @{ ;
                             if (ViewBag.Evaluateur == true)
                             {
                                <label>Collaborateur Evaluateur</label>
                             }
                             else
                             {<label>Collaborateur Non Evaluateur</label> }
                            }

                        </div>
                    </div>
                    <!-- END SIDEBAR USER TITLE -->
                    <!-- SIDEBAR BUTTONS -->
                   
                    <div class="profile-userbuttons">

                        @Html.ActionLink("Modifier La photo", "EditImage", "Collaborateur", new { id = Model.IDCOLLABORATEUR }, new { @class = "btn btn-circle green-haze btn-sm" })
                        @{if (User.IsInRole("superuser"))
                        {  @Html.ActionLink("Retour a la List", "Index", null, new { @class = "btn btn-circle btn-danger btn-sm" })

                        }}
                    </div>
                    <!-- END SIDEBAR BUTTONS -->
                    <!-- SIDEBAR MENU -->
                    <!-- END MENU -->
                </div>
                <!-- END PORTLET MAIN -->
                <!-- PORTLET MAIN -->
                <!-- END STAT -->
            </div>
            <!-- END PORTLET MAIN -->

        </center>

    </div>
</div>

source/ProjetGestionEval/ProjetGestionEval/Views/Collaborateur/Edit.cshtml
@model ProjetGestionEval.collaborateur

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}
<ul class="page-breadcrumb breadcrumb">
    <li>

        <a href="~/Home/Accueil">Acceuil</a>
        <i class="fa fa-circle"></i>
        <a href="~/Collaborateur/Index">Liste des Collaborateurs</a>
        <i class="fa fa-circle"></i>
        <a href="~/Collaborateur/Edit/@Model.IDCOLLABORATEUR">Modifier</a>
        <i class="fa fa-circle"></i>
    </li>

</ul>


<div class="row">
    <div class="col-md-12">
        <div class="col-md-4">
            <!-- BEGIN PROFILE SIDEBAR -->
            <div class="profile-sidebar">
                <!-- PORTLET MAIN -->
                <div class="portlet light profile-sidebar-portlet">
                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">
                        <img src="data:image/png;base64,@Convert.ToBase64String(Model.IMAGE, 0,Model.IMAGE.Length)" class="img-responsive" />
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name">

                            @Html.DisplayFor(model => model.NOM)
                            @Html.DisplayFor(model => model.PRENOM)

                        </div>
                        <div class="profile-usertitle-job">
                            @Html.DisplayFor(model => model.fonction.NOMFONCTION)
                        </div>
                    </div>
                    <!-- END SIDEBAR USER TITLE -->
                    <!-- SIDEBAR BUTTONS -->
                    <!-- END SIDEBAR BUTTONS -->
                    <!-- SIDEBAR MENU -->
                    <div class="profile-usermenu">

                    </div>
                    <!-- END MENU -->
                </div>
                <!-- END PORTLET MAIN -->
                <!-- PORTLET MAIN -->
                <!-- END STAT -->
            </div>
            <!-- END PORTLET MAIN -->
        </div>
        <!-- END BEGIN PROFILE SIDEBAR -->
        <!-- BEGIN PROFILE CONTENT -->
        <div class="col-md-8">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light">
                <div class="portlet-title tabbable-line">
                    <div class="caption caption-md">
                        <i class="icon-globe theme-font hide"></i>
                        <span class="caption-subject font-blue-madison bold uppercase">Profile Collaborateur Titulaire</span>
                    </div>
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#tab_1_1" data-toggle="tab">Personal Info</a>
                        </li>
                    </ul>
                </div>
                <div class="portlet-body form">
                    @using (Html.BeginForm("Edit","Collaborateur",FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.IDCOLLABORATEUR)


                            <div class="form-group">
                                @Html.LabelFor(model => model.NOM, "Nom", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        @Html.EditorFor(model => model.NOM, new { htmlAttributes = new { @class = "form-control"} })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.PRENOM, "Prenom", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        @Html.EditorFor(model => model.PRENOM, new { htmlAttributes = new { @class = "form-control"} })
                                    </div>
                                </div>
                            </div>





                            <div class="form-group">
                                @Html.LabelFor(model => model.DATEEMBAUCHE, "Date d'embauche", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-3">
                                    <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                        @{
                        bd_gestionEntities bd = new bd_gestionEntities();

                        var xy = bd.collaborateur.Find(Model.IDCOLLABORATEUR).DATEEMBAUCHE;
                                        }
                                        <input type="text" name="DATEEMBAUCHE" class="form-control" value=@xy>
                                        <span class="input-group-btn">
                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                        </span>
                                    </div>

                                    <!-- /input-group -->
                                    <span class="help-block">
                                        Select date
                                    </span>
                                </div>
                            </div>

                      
                                
                                
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DATESORTIE, "Date de sortie", htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-3">
                                        <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                            @{

                        var x = Model.DATESORTIE;

                                            }

                                            <input type="text" name="DATESORTIE" class="form-control" value=@x>
                                            <span class="input-group-btn">
                                                <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                            </span>
                                        </div>

                                        <!-- /input-group -->
                                        <span class="help-block">
                                            Select date
                                        </span>
                                    </div>
                                </div>
                             
                            

                            <div class="form-group">

                                @Html.LabelFor(model => model.aspnetusers.Email, "Email", htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="fa fa-envelope"></i>
                                        </span>
                                        @Html.EditorFor(model => model.aspnetusers.Email, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                                    </div>
                                </div>
                            </div>



                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Fonction <span class="required">
                                        *
                                    </span>
                                </label>
                                <div class="col-md-4">
                                    @Html.DropDownListFor(M => M.IDFONCTION, ViewBag.IDFONCTION as SelectList, null, htmlAttributes: new { @Class = "form-control", required = "required" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Collaborateur
                                </label>
                                <div class="col-md-4">
                                    <div class="radio-list" data-error-container="#form_2_membership_error">
                                        <label>
                                            @Html.RadioButtonFor(M => M.TYPECOLLABORATEUR, "Freelance", new { @class = "enable_tb" })
                                            Freelance
                                        </label>
                                        <label>
                                            @Html.RadioButtonFor(M => M.TYPECOLLABORATEUR, "Titulaire")
                                            Titulaire
                                        </label>
                                        <label>
                                            @Html.RadioButtonFor(M => M.TYPECOLLABORATEUR, "P.E", new { @class = "enable_tb" })
                                            Periode d'esseai
                                        </label>
                                    </div>
                                    <div id="form_2_membership_error">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3">
                                    Evaluateur
                                </label>
                                <div class="col-md-4">
                                    <div class="radio-list" data-error-container="#form_2_membership_error">
                                        <label>
                                            @Html.RadioButtonFor(M => M.FLAGEVAL, true, htmlAttributes: new { id = "otherDevText", @disabled = "disabled" })
                                            Oui
                                        </label>
                                        <label>
                                            @Html.RadioButtonFor(M => M.FLAGEVAL, false, htmlAttributes: new { id = "otherDevText2", @disabled = "disabled" })
                                            Non
                                        </label>
                                    </div>
                                    <div id="form_2_membership_error">
                                    </div>
                                </div>
                            </div>

                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn green">Sauvegarder</button>
                                        <a href="@Url.Action("Index")" class="btn default">Retour</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }                    
                </div>
            </div>
        </div>
    </div>
</div>