source/ProjetGestionEval/ProjetGestionEval/Controllers/ProjetController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ProjetGestionEval.Controllers
{
    public class ProjetController : Controller
    {
        static string ConnectionString = "database=bd_gestion;server=localhost;uid=root";
        MySqlConnection Connection = new MySqlConnection(ConnectionString);
        bd_gestionEntities bd = new bd_gestionEntities();
        // GET: Projet
        public ActionResult Index()
        {
            return View(bd.projet.ToList());
        }
        public ActionResult IndexPr()
        {
            var asp = bd.aspnetusers.Where(i => i.Email == User.Identity.Name).FirstOrDefault();
            var ctn = bd.collaborateur.Single(m => m.IdUser == asp.Id);
            var id = ctn.IDCOLLABORATEUR;
            Connection.Open();
            string req = "SELECT IDPROJET FROM administrer where IDCOLLABORATEUR=" + id ;
            //SELECT * FROM projet where IDPROJET IN (SELECT IDPROJET FROM administrer where IDCOLLABORATEUR=" + id+")
            MySqlCommand cmd = new MySqlCommand(req, Connection);
            MySqlDataReader dr = cmd.ExecuteReader();
            
              List<String> s1=new List<string>();
          
            while (dr.Read())
            {
                s1.Add(dr[0].ToString());
                
            }
            
            //int s = 0;
            
            //if (s1 != null) { s = int.Parse(s1); }
            ViewBag.ss=s1.Select(int.Parse).ToList();


            return View(bd.projet.ToList());
        }
        // GET: Projet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            projet pr = bd.projet.Find(id);
            if (pr == null)
                return HttpNotFound();


            return View(pr);
        }

        // GET: Projet/Create
        public ActionResult Create()
        {
            //.Where(m => m.TYPECOLLABORATEUR=="collabpe")
            ViewBag.collaborateur = new SelectList(bd.collaborateur.Where(m => m.TYPECOLLABORATEUR == "Titulaire"), "IDCOLLABORATEUR", "NOM");
            ViewBag.collaborateurpe = new SelectList(bd.collaborateur.Where(m => m.TYPECOLLABORATEUR == "P.E"), "IDCOLLABORATEUR", "NOM");
            ViewBag.client = new SelectList(bd.client, "IDCLIENT", "ABREVIATION");

            return View();
        }

        // POST: Projet/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "collaborateur")]projet Projet, FormCollection fc)
        {
            var testid = fc["collaborateur"];
            string[] testids = testid.Split(',');
            foreach (var item in testids)
            {
                int b = int.Parse(item);
                Projet.collaborateur.Add(bd.collaborateur.Where(m => m.IDCOLLABORATEUR == b).FirstOrDefault());
            }

            ViewBag.collaborateur = new MultiSelectList(bd.collaborateur, "IDCOLLABORATEUR", "NOM");
            
            ViewBag.client = new SelectList(bd.client, "IDCLIENT", "ABREVIATION");
            Projet.client = bd.client.Single(m => m.IDCLIENT == Projet.IDCLIENT);
            try
            {

                if (ModelState.IsValid)
                {

                    var y = bd.projet.Add(Projet);
                    bd.SaveChanges();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Projet/Edit/5
        public ActionResult Edit(int? id)
        {
           
           ViewBag.collaborateur = new SelectList(bd.collaborateur.Where(m => m.TYPECOLLABORATEUR == "Titulaire"), "IDCOLLABORATEUR", "NOM");
           ViewBag.collaborateurpe = new SelectList(bd.collaborateur.Where(m => m.TYPECOLLABORATEUR == "P.E"), "IDCOLLABORATEUR", "NOM");

           List<String> ct=new List<string>();
           var tab = bd.projet.Find(id).collaborateur.Where(m=>m.TYPECOLLABORATEUR=="Titulaire");
           foreach (var cc in tab)
           {
               ct.Add(cc.NOM);
               
           }
           ViewBag.ct = ct;
           List<String> cp = new List<string>();
           var tab2 = bd.projet.Find(id).collaborateur.Where(m => m.TYPECOLLABORATEUR == "P.E");
           foreach (var cc in tab2)
           {
               cp.Add(cc.NOM);

           }
           ViewBag.cp = cp;

            //ViewBag.collaborateur = new MultiSelectList(vv, "IDCOLLABORATEUR", "NOM");
           
            ViewBag.IDCLIENT = new SelectList(bd.client, "IDCLIENT", "ABREVIATION", bd.projet.Find(id).client.IDCLIENT);


            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            projet col = bd.projet.Find(id);

            if (col == null)
                return HttpNotFound();
            return View(col);
        }

        // POST: Projet/Edit/5
        [HttpPost]
        public ActionResult Edit(int? id, [Bind(Exclude = "collaborateur")]projet pro, FormCollection fc)
        {
            ViewBag.collaborateurtitulaire = new MultiSelectList(bd.collaborateur, "IDCOLLABORATEUR", "NOM");
           
            ViewBag.IDCLIENT = new SelectList(bd.client, "IDCLIENT", "ABREVIATION");

            projet p = bd.projet.Find(id);
            p.IDPROJET = (int)id;
            p.NOMPROJET = pro.NOMPROJET;
            p.DATEDEBUT = pro.DATEDEBUT;
            p.DATEFIN = pro.DATEFIN;
            p.TYPE = pro.TYPE;
            p.IDCLIENT = pro.IDCLIENT;
            p.client = bd.client.Single(m => m.IDCLIENT == pro.IDCLIENT);
            p.FLAGTYPE = pro.FLAGTYPE;
            var testid = fc["collaborateur"];
            string[] testids = testid.Split(',');
            p.collaborateur.Clear();
            foreach (var item in testids)
            {
                int b = int.Parse(item);
                p.collaborateur.Add(bd.collaborateur.Where(m => m.IDCOLLABORATEUR == b).FirstOrDefault());
            }
           

            try
            {
                if (ModelState.IsValid)
                {
                    bd.Entry(p).State = System.Data.Entity.EntityState.Modified;



                    bd.SaveChanges();
                    return RedirectToAction("Index");


                }
                return View(p);
            }
            catch
            {
                return View();
            }
        }

        // GET: Projet/Delete/5
        public ActionResult Delete(int? id)
        {
            projet bb = bd.projet.Find(id);
            var x = "";
            if (bb.TYPE == 2) { x = "Régie"; }
            else if (bb.TYPE == 1) { x = "TMA"; }
            else { x = "Forfait"; }

            ViewBag.Type = x;
            var z = "";
            if (bb.FLAGTYPE == true)
            {
                z = "Interne";
            }
            else
            {
                z = "Externe";
            } ViewBag.flag = z;

            ViewBag.datedebut = bb.DATEDEBUT.Value.Day.ToString() + "/" + bb.DATEDEBUT.Value.Month.ToString() + "/" + bb.DATEDEBUT.Value.Year.ToString();
            ViewBag.datedefin = bb.DATEFIN.Value.Day.ToString() + "/" + bb.DATEFIN.Value.Month.ToString() + "/" + bb.DATEFIN.Value.Year.ToString();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            projet colpe = bd.projet.Find(id);
            if (colpe == null)
            {
                return HttpNotFound();
            }
            return View(colpe);
        }

        // POST: Projet/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id, projet pro)
        {
            Connection.Open();
            string req = "Delete From administrer Where IDPROJET=" + id+"; Delete From tache Where IDPROJET=" + id;
            MySqlCommand cmd = new MySqlCommand(req, Connection);
           
            cmd.ExecuteNonQuery();
            
           
            
            try
            {
                projet colpe = new projet();

                //if (ModelState.IsValid)
                //{
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                    colpe = bd.projet.Find(id);

                    if (colpe == null)
                        return HttpNotFound();


                    bd.projet.Remove(colpe);
                

                    bd.SaveChanges();
                    return RedirectToAction("Index");

                //} return View(colpe);
            }

            catch(Exception ex){
                ex.ToString();
                return View();
            }
        }
    }
}

source/ProjetGestionEval/ProjetGestionEval/Views/Projet/Create.cshtml
@model ProjetGestionEval.projet

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}

<ul class="page-breadcrumb breadcrumb">
    <li>

        <a href="~/Home/Accueil">Accueil</a>
        <i class="fa fa-circle"></i>
        <a href="~/Projet/Index">Liste des projets</a>
        <i class="fa fa-circle"></i>
        <a href="~/Projet/Create">Ajouter</a>
        <i class="fa fa-circle"></i>
    </li>

</ul>
<div class="col-md-12">
    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet box red">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-plus-square"></i>Projet
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse">
                </a>
                <a href="#portlet-config" data-toggle="modal" class="config">
                </a>
                <a href="javascript:;" class="reload">
                </a>
                <a href="javascript:;" class="remove">
                </a>
            </div>
        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <form action="Create" method="Post" id="form_sample_3" class="form-horizontal" enctype="multipart/form-data">
                <div class="form-body">
                    <div class="alert alert-danger display-hide">
                        <button class="close" data-close="alert"></button>
                        Vous avez oubliez des champs. Veuillez s'il vous plait revérifier.
                    </div>
                    <div class="alert alert-success display-hide">
                        <button class="close" data-close="alert"></button>
                        Le projet a ete ajouter avec succes
                    </div>






                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @*<div class="form-group">
                                @Html.LabelFor(model => model.IDCLIENT, "IDCLIENT", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("IDCLIENT", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IDCLIENT, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.NOMPROJET, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.NOMPROJET, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NOMPROJET, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">

                            <label class="control-label col-md-3">Collaorateur titulaire</label>
                            <div class="col-md-4">

                                @Html.ListBoxFor(m => m.collaborateur, ViewBag.collaborateur as MultiSelectList, htmlAttributes: new { @Class = "bs-select form-control", @multiple = "multiple", required = "required" })

                            </div>

                        </div>

                        <div class="form-group">

                            <label class="control-label col-md-3">Collaorateur P.E</label>
                            <div class="col-md-4">

                                @Html.ListBoxFor(m => m.collaborateur, ViewBag.collaborateurpe as MultiSelectList, htmlAttributes: new { @Class = "bs-select form-control", @multiple = "multiple", required = "required" })

                            </div>

                        </div>

                        @*<div class="form-group">
                            <label class="control-label col-md-3">Collaborateur en Esseai</label>
                            <div class="col-md-4">
                                @Html.ListBoxFor(m => m.collaborateurpe, ViewBag.collaborateurpe as MultiSelectList, htmlAttributes: new { @Class = "bs-select form-control", @multiple = "multiple", required = "required" })
                            </div>
                        </div*@>
                        <div class="form-group">
                            <label class="control-label col-md-3">Client Du Projet</label>
                            <div class="col-md-4">
                                @Html.DropDownListFor(m => m.IDCLIENT, ViewBag.Client as SelectList, "Selectionner le Client", htmlAttributes: new { @Class = "form-control", required = "required" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Date Debut Projet</label>
                            <div class="col-md-3">
                                <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                    <input type="text" class="form-control" name="DATEDEBUT">
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                    </span>
                                </div>
                                <!-- /input-group -->
                                <span class="help-block">
                                    Select date
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Date Fin Projet</label>
                            <div class="col-md-3">
                                <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                    <input type="text" class="form-control" name="DATEFIN">
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                    </span>
                                </div>
                                <!-- /input-group -->
                                <span class="help-block">
                                    Select date
                                </span>
                            </div>
                        </div>

                        <div class="form-group ">
                            @Html.LabelFor(model => model.TYPE, "Type de Projet", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-5">
                                <div class="md-radio-inline">
                                    <div class="md-radio">
                                        <input type="radio" id="radio53" name="TYPE" value="2" class="md-radiobtn">
                                        <label for="radio53">
                                            <span></span>
                                            <span class="check"></span>
                                            <span class="box"></span>
                                            Régie
                                        </label>
                                    </div>

                                    <div class="md-radio">
                                        <input type="radio" id="radio54" name="TYPE" value="1" class="md-radiobtn" checked>
                                        <label for="radio54">
                                            <span></span>
                                            <span class="check"></span>
                                            <span class="box"></span>
                                            TMA
                                        </label>
                                    </div>
                                    <div class="md-radio">
                                        <div class="md-radio">
                                            <input type="radio" id="radio55" name="TYPE" value="0" class="md-radiobtn">
                                            <label for="radio55">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Forfait
                                            </label>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Projet</label>
                            <div class="col-md-5">
                                <div class="md-radio-inline">
                                    <div class="md-radio">
                                        <input type="radio" id="radio56" name="FLAGTYPE" value=true class="md-radiobtn">
                                        <label for="radio56">
                                            <span></span>
                                            <span class="check"></span>
                                            <span class="box"></span>
                                            Interne
                                        </label>
                                    </div>

                                    <div class="md-radio">
                                        <div class="md-radio">
                                            <input type="radio" id="radio57" name="FLAGTYPE" value=false class="md-radiobtn" checked>
                                            <label for="radio57">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Externe
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn green">Sauvegarder</button>
                            
                            <a href="@Url.Action("Index")" class="btn default">Retour</a>
                        </div>
                    </div>
                </div>

            </form>
            <!-- END FORM-->
        </div>
        <!-- END VALIDATION STATES-->
    </div>
</div>

source/ProjetGestionEval/ProjetGestionEval/Views/Projet/Edit.cshtml
@model ProjetGestionEval.projet

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}

<ul class="page-breadcrumb breadcrumb">
    <li>

        <a href="~/Home/Accueil">Accueil</a>
        <i class="fa fa-circle"></i>
        <a href="~/Projet/Index">Liste des projets</a>
        <i class="fa fa-circle"></i>
        <a href="~/Projet/Edit/@Model.IDPROJET">Modifier</a>
        <i class="fa fa-circle"></i>
    </li>

</ul>
<div class="row">
    <div class="col-md-12">




        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-equalizer font-red-sunglo"></i>

                    <span class="caption-helper">Projet de </span>
                    <span class="caption-subject font-red-sunglo bold uppercase">@Model.client.ABREVIATION</span>
                </div>

            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
               @using (Html.BeginForm("Edit", "Projet", FormMethod.Post, new { htmlAttributes = new { @class = "form-horizontal" } }))
               {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.IDPROJET)
                        <div class="form-body">

                            <div class="form-group">
                                @Html.LabelFor(model => model.IDCLIENT, "Client", htmlAttributes: new { @class = "col-md-3 control-label" })
                                <div class="col-md-4">
                                    @*@Html.DropDownList("IDCLIENT", null, htmlAttributes: new { @class = "form-control" })*@
                                    @Html.DropDownList("IDCLIENT", null, htmlAttributes: new { @class = "bs-select form-control", required = "required" })
                                    @*@Html.DropDownListFor(m => m.IDCLIENT, ViewBag.IDCLIENT as SelectList, htmlAttributes: new { @Class = "bs-select form-control", required = "required" })*@
                                    @Html.ValidationMessageFor(model => model.IDCLIENT, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.NOMPROJET, "Nom de projet", htmlAttributes: new { @class = "col-md-3 control-label" })
                                <div class="col-md-4">
                                    @Html.EditorFor(model => model.NOMPROJET, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NOMPROJET, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3">Date Debut Projet</label>
                                <div class="col-md-3">
                                    <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                        <input type="text" class="form-control" value=@Model.DATEDEBUT name="DATEDEBUT">
                                        <span class="input-group-btn">
                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                        </span>
                                    </div>
                                    <!-- /input-group -->
                                    <span class="help-block">
                                        Select date
                                    </span>
                                </div>
                            </div>


                            <div class="form-group">
                                <label class="control-label col-md-3">Date Fin Projet</label>
                                <div class="col-md-3">
                                    <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                        <input type="text" class="form-control" value=@Model.DATEFIN name="DATEFIN">
                                        <span class="input-group-btn">
                                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                        </span>
                                    </div>
                                    <!-- /input-group -->
                                    <span class="help-block">
                                        Select date
                                    </span>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.collaborateur, "Collaborateur Titulaire", htmlAttributes: new { @class = "col-md-3 control-label" })
                                @{
                                    string x = "";
                                    foreach (var s in ViewBag.ct) {

                                        x = x + s+"," ;
                                  
                                  }
               }
                                <div class="col-md-4">

                                    @Html.DropDownListFor(m => m.collaborateur, ViewBag.collaborateur as MultiSelectList, htmlAttributes: new { @Class = "bs-select form-control",@multiple = "multiple",title=@x, required = "required"})
                                    @Html.ValidationMessageFor(model => model.collaborateur, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.collaborateur, "Collaborateur P.E", htmlAttributes: new { @class = "col-md-3 control-label" })
                                @{
                                    string y = "";
                                    foreach (var s in ViewBag.cp)
                                    {

                                        y = y + s + ",";

                                    }
                                }
                                <div class="col-md-4">

                                    @Html.DropDownListFor(m => m.collaborateur, ViewBag.collaborateurpe as MultiSelectList, htmlAttributes: new { @Class = "bs-select form-control",title=@y
, @multiple = "multiple"})
                                    @Html.ValidationMessageFor(model => model.collaborateur, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            @*<div class="form-group">
                                @Html.LabelFor(model => model.collaborateurpe, "Collaborateur P.E", htmlAttributes: new { @class = "col-md-3 control-label" })
                                <div class="col-md-4">

                                    @Html.DropDownListFor(m => m.collaborateurpe, ViewBag.collaborateurpe as MultiSelectList, htmlAttributes: new { @Class = "bs-select form-control", @multiple = "multiple", required = "required" })
                                    @Html.ValidationMessageFor(model => model.collaborateurpe, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                            <div class="form-group">
                                @Html.LabelFor(model => model.TYPE, "Type projet", htmlAttributes: new { @class = "col-md-3 control-label" })
                                <div class="radioLeft col-sm-8">
                                    @Html.RadioButtonFor(model => model.TYPE, "2")Régie
                                    @Html.RadioButtonFor(model => model.TYPE, "1")TMA
                                    @Html.RadioButtonFor(model => model.TYPE, "0")Forfait

                                    @Html.ValidationMessageFor(model => model.TYPE, "", new { @class = "text-danger" })

                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.FLAGTYPE, "Interne/Externe", htmlAttributes: new { @class = "col-md-3 control-label" })
                                <div class="radioLeft col-sm-8">
                                    @Html.RadioButtonFor(model => model.FLAGTYPE, "true") Interne
                                    @Html.RadioButtonFor(model => model.FLAGTYPE, "false") Externe


                                    @Html.ValidationMessageFor(model => model.TYPE, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>
                            <div class="row">

                                <div class="col-md-offset-3 col-md-9">
                                  
                                        <input type="submit" value="Sauvegarder" class="btn red-haze" />@Html.ActionLink("Retour à la liste", "Index", null, new { @class = "btn default" })
                                </div>
                            </div>
                    </div>
                }
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>