source/ProjetGestionEval/ProjetGestionEval/Controllers/EvaluationController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ProjetGestionEval.Controllers
{
    public class EvaluationController : Controller
    {
        public static string[][] chartRes = new string[3][];
        public static int max = 0;
        static string ConnectionString = "database=bd_gestion;server=localhost;uid=root";
        MySqlConnection Connection = new MySqlConnection(ConnectionString);
        // GET: Evaluation

        //static string ConnectionString = "database=bd_gestion;server=localhost;uid=root";
        //MySqlConnection Connection = new MySqlConnection(ConnectionString);
        bd_gestionEntities bd = new bd_gestionEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IndexCol()
        {
            return View(bd.collaborateur.Where(m=>m.FLAGEVAL==false).ToList());
        }
        // GET: Evaluation/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.id = id;
            
            string[] months = new string[] { "January", "February", "March", "April", "May", "June", "July", "Aout", "September", "Octore", "Novemre", "Decemre" };
            Connection.Open();
            for (int i = 0; i < 3; i++)
            {chartRes[i] = new string[12];}
            MySqlCommand cmd = new MySqlCommand("SELECT month(t.DATEFINTACHE),Year(t.DATEFINTACHE),COUNT(*) tache from tache t where IdCollaborateur = @col and t.DATEFINTACHE between(select DateEvaluation from Evaluation where IdCollaborateur = @col) and (select DateNextEvaluation from Evaluation where IdCollaborateur = @col) group by Year(t.DATEFINTACHE),month(t.DATEFINTACHE)", Connection);
            cmd.Parameters.AddWithValue("@col", id);
            MySqlCommand cmd1 = new MySqlCommand("SELECT month(p.DATEFIN),Year(p.DATEFIN),COUNT(*) from projet p where Idprojet in (select Idprojet from administrer where IdCollaborateur = @col) and p.DATEFIN between(select DateEvaluation from Evaluation where IdCollaborateur = @col) and (select DateNextEvaluation from Evaluation where IdCollaborateur = @col)  group by Year(p.DATEFIN),month(p.DATEFIN)", Connection);
            cmd1.Parameters.AddWithValue("@col", id);
            MySqlDataReader mdr = cmd.ExecuteReader();
            while(mdr.Read())
            {

                chartRes[0][int.Parse(mdr[0].ToString()) - 1] = months[int.Parse(mdr[0].ToString()) - 1];//mdr[0].ToString();
                chartRes[1][int.Parse(mdr[0].ToString()) - 1] = mdr[2].ToString();

            }
            string tst = null, tst1 = null;
            mdr.Close();
            cmd.Dispose();
            mdr = cmd1.ExecuteReader();
            while (mdr.Read())
            {
                tst = mdr[0].ToString();
                tst1 = mdr[1].ToString();
                if (chartRes[0][int.Parse(mdr[0].ToString()) - 1] == null) chartRes[0][int.Parse(mdr[0].ToString()) - 1] = months[int.Parse(mdr[0].ToString()) - 1];
                chartRes[2][int.Parse(mdr[0].ToString()) - 1] = mdr[2].ToString();

            }
            for (int i = 0; i < 12;i++)
            {
                if (chartRes[0][i] == null) chartRes[0][i] =  months[i];
                if (chartRes[1][i] == null) chartRes[1][i] = (0).ToString();
                if (chartRes[2][i] == null) chartRes[2][i] = (0).ToString();
            }
            return View(bd.evaluation.Where(e => e.IDCOLLABORATEUR == id).OrderByDescending(e => e.DATEEVALUATION).First());
        }
        public ActionResult getData()
        {
            for (int i = 1;i<3;i++)
            {
                for (int y = 0; y < 12; y++)
                {
                    if (int.Parse(chartRes[i][y]) > max) max = int.Parse(chartRes[i][y]);
                }
            }
            var serializer = new JavaScriptSerializer();
            serializer.MaxJsonLength = Int32.MaxValue;
            var resultData = new
            {
                Content = chartRes,
                maxVal = max
            };
            var result = new ContentResult
            {
                Content = serializer.Serialize(resultData),
                ContentType = "application/json"
            };

            return result;
        }
        // GET: Evaluation/Create
        public ActionResult Create(int? id)
        {
            ViewBag.id = id;
            return View();
        }

        // POST: Evaluation/Create
        [HttpPost]
        public ActionResult Create(int? id, [Bind(Exclude = "")]evaluation ev, FormCollection collection)
        {
            var dt= DateTime.Now;
            ev.DATEEVALUATION = dt;
            ev.DATENEXTEVALUATION = dt.AddMonths(15);
            var id1 = collection["IDEVALUATEUR"];
            var id2 = collection["IDCOLLABORATEUR"];
          
            var bb = bd.tache.Where(m => m.IDCOLLABORATEUR == id).ToList();
            int i = 0;
            foreach (var item in bb) {
                string f = i.ToString();
                item.NoteTache = collection[f];

                bd.Entry(item).State = System.Data.Entity.EntityState.Modified;
                

                ++i;
            }
            int j = 0;
            var fm = bd.famillecritere.ToList();
            foreach (var it in fm)
            {
                var cr = bd.critere.Where(m => m.IDFAMILLECRITERE == it.IDFAMILLECRITERE);

                foreach (var item in cr)
                {string d=j.ToString();
                    item.NoteCritere = collection[d];
                    //bd.Entry(item).State = System.Data.Entity.EntityState.Modified;
                    ev.critere.Add(item);
                    j++;
                }
            }
            var col = bd.collaborateur.Find(id);
            col.Evaluer = true;
            if (ev.STATUT == "titulaire")
            {
                
                col.TYPECOLLABORATEUR = "Titulaire";
                

            }
            bd.Entry(col).State = System.Data.Entity.EntityState.Modified;
            try
            {
                //if (ModelState.IsValid)
                //{

                    bd.evaluation.Add(ev);
                    bd.SaveChanges();
                //    return RedirectToAction("IndexCol");
                //}
                return RedirectToAction("IndexCol");
            }
            catch(Exception ex)
            {
                ex.ToString();
                return View();
            }
            
        }

        // GET: Evaluation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Evaluation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Evaluation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Evaluation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

source/ProjetGestionEval/ProjetGestionEval/Views/Evaluation/Delete.cshtml
@model ProjetGestionEval.evaluation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>evaluation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DATEEVALUATION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATEEVALUATION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATENEXTEVALUATION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATENEXTEVALUATION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.APPRECIATION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.APPRECIATION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.collaborateur.NOM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.collaborateur.NOM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.collaborateur1.NOM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.collaborateur1.NOM)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

source/ProjetGestionEval/ProjetGestionEval/Views/Evaluation/Details.cshtml
@model ProjetGestionEval.evaluation

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}

<ul class="page-breadcrumb breadcrumb">
    <li>


        <a href="~/Home/Accueil">Accueil</a>
        <i class="fa fa-circle"></i>
        <a href="~/Evaluation/IndexCol">Liste des Collaborateur</a>
        <i class="fa fa-circle"></i>
        <a href="~/Evaluation/Details/@Model.IDCOLLABORATEUR">Details</a>
        <i class="fa fa-circle"></i>
    </li>

</ul>



<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>



<div class="row">
    @{bd_gestionEntities d = new bd_gestionEntities();
    collaborateur coll = d.collaborateur.Find(ViewBag.id);
    }
    <div class="col-md-12">
        <div class="col-md-4">
            <!-- BEGIN PROFILE SIDEBAR -->
            <div class="profile-sidebar">
                <!-- PORTLET MAIN -->
                <div class="portlet light profile-sidebar-portlet">
                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">

                        <img src="data:image/png;base64,@Convert.ToBase64String(coll.IMAGE, 0,coll.IMAGE.Length)" class="img-responsive" />
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name">

                            @Html.DisplayFor(model => coll.NOM)
                            @Html.DisplayFor(model => coll.PRENOM)<br />
                            @Html.DisplayFor(model => coll.TYPECOLLABORATEUR)
                        </div>
                        <div class="profile-usertitle-job">
                            @Html.DisplayFor(model => coll.fonction.NOMFONCTION)
                            
                            <br/><label>Date Evaluation</label><br /><label> @Model.DATEEVALUATION</label>

</div>
                    </div>
                    <!-- END SIDEBAR USER TITLE -->
                    <!-- SIDEBAR BUTTONS -->
                    <!-- END SIDEBAR BUTTONS -->
                    <!-- SIDEBAR MENU -->
                    <div class="profile-usermenu">

                    </div>
                    <!-- END MENU -->
                </div>
                <!-- END PORTLET MAIN -->
                <!-- PORTLET MAIN -->
                <!-- END STAT -->
            </div>
            <!-- END PORTLET MAIN -->
        </div>
        <div class=" col-md-8">
            <label>Date Prochaine Evaluation</label>
                   <label> @Model.DATENEXTEVALUATION</label>
            <div class="portlet light" style="padding: 20px 31px 130px 20px;">
                <center>
                    <div id="Chart2Container" style="width: 75%;">
                        <canvas id="canvas_bar2"></canvas>
                    </div>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            $.ajax({
                                url: "@Url.Action("getData", "Evaluation")",

                                type: "POST",
                                dataType: "Json",
                                success: function (data) {
                                    console.log("test" + data.Content);
                                    mychart(data.Content, data.maxVal);
                                },

                            });

                        });
                        function mychart(params, max) {
                            //console.log(params[0]);
                            var barChartData = {
                                //labels: ["January", "February", "March", "April", "May", "June", "July", "Aout", "September"],
                                labels: params[0],
                                datasets: [
                                    {
                                        fillColor: "#26B99A", //rgba(220,220,220,0.5)
                                        strokeColor: "#26B99A", //rgba(220,220,220,0.8)
                                        highlightFill: "#36CAAB", //rgba(220,220,220,0.75)
                                        highlightStroke: "#36CAAB", //rgba(220,220,220,1)
                                        data: params[1]//[70, 60, 20, 88, 12, 60, 35, 90, 95]
                                    },
                                    {
                                        fillColor: "#03586A", //rgba(151,187,205,0.5)
                                        strokeColor: "#03586A", //rgba(151,187,205,0.8)
                                        highlightFill: "#066477", //rgba(151,187,205,0.75)
                                        highlightStroke: "#066477", //rgba(151,187,205,1)
                                        data: params[2]//[41, 56, 25, 48, 72, 34, 12, 45, 40]
                                    },
                                ],
                            }

                            $("#canvas_bar2").remove();
                            $('#Chart2Container').append('<canvas id="canvas_bar2" ><canvas>');
                            new Chart($("#canvas_bar2").get(0).getContext("2d")).Bar(barChartData, {
                                tooltipFillColor: "rgba(51, 51, 51, 0.55)",
                                responsive: true,
                                maintainAspectRatio: true,
                                barDatasetSpacing: 2,
                                barValueSpacing: 7,
                                scaleOverride: true,
                                scaleSteps: max,
                                scaleStepWidth: 2,
                                scaleStartValue: 0
                            });
                        }

                    </script>
                </center>
                <div class="form-group">
                    <label class="col-md-2 control-label">
                        Note Taches:
                    </label>
                    <div class="col-md-10">
                        <div class="form-control height-auto">
                            <div class="scroller" style="height:100px;" data-always-visible="1">
                                @{
                                    int x = 0;
                                    if (ViewBag.id != null)
                                    {
                                        x = ViewBag.id;
                                        var dd = d.tache.Where(m => m.IDCOLLABORATEUR == x).ToList();
                                        int i = 0;

                                        foreach (var item in dd)
                                        {
                                            string c = i.ToString();

                                            <div class="form-group">
                                                @Html.LabelFor(modelItem => item.NOMTACHE, item.NOMTACHE, new { @class = "control-label col-md-2" })
                                                <div>
                                                    @Html.LabelFor(modelItem => item.NoteTache, item.NoteTache, new { @class = "btn btn-icon-only green" })

                                                </div>
                                            </div>
                                            ++i;
                                        }
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <br/>
                <div class="form-group">
                    <label class="col-md-2 control-label" style="margin-top: 2%">
                        Note Categories:
                    </label>
                    @{
                        int r = 0;
                        bd_gestionEntities f = new bd_gestionEntities();
                        var fax = f.famillecritere.ToList();
                        <div class="col-md-10" style="margin-top: 2%">
                            <div class="form-control height-auto">
                                <div class="scroller" style="height: 275px;width: 730px;overflow: hidden;" data-always-visible="1">

                                    @foreach (var it in fax)
                                    {

                                        <ul>
                                            <li>
                                                @Html.LabelFor(modelItem => it.NOMFAMILLECRITERE, it.NOMFAMILLECRITERE)

                                                @{var fat = f.critere.Where(m => m.IDFAMILLECRITERE == it.IDFAMILLECRITERE); }
                                                @foreach (var item in fat)
                                                {
                                                    string t = r.ToString();
                                                    <ul>
                                                        <li>
                                                            <div class="md-radio-inline">
                                                                @Html.LabelFor(modelItem => item.NOMCRITERE, item.NOMCRITERE, new { @class = "col-md-5" })
                                                                <div>
                                                                    @Html.LabelFor(modelItem => item.NoteCritere, item.NoteCritere, new { @class = "btn btn-icon-only green" })

                                                                </div>
                                                                <br />
                                                            </div>
                                                        </li>
                                                    </ul>
                                                    r++;
                                                }
                                                <br />
                                            </li>
                                        </ul>

                                    }
                                </div>
                            </div>
                        </div>
                    }
                </div>
                
                <div class="form-group">
                    <label class="control-label col-md-3" style="margin-left: -1%;margin-top: 6%;">Remarque:</label>
                    <div class="col-md-6">
                     @Html.TextArea("Memo", @Model.Memo, new { @class = "form-control" ,@style="margin-top: 6%;margin-left: -15%;width: 173%;" }) 
                    </div>
                </div>
                <br />
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <a href="@Url.Action("IndexCol")" class="btn default" style="    margin-top: 5%;margin-left: 28%;">Retour</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

source/ProjetGestionEval/ProjetGestionEval/Views/Evaluation/Edit.cshtml
@model ProjetGestionEval.evaluation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>evaluation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDEVALUATION)

        <div class="form-group">
            @Html.LabelFor(model => model.IDEVALUATEUR, "IDEVALUATEUR", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDEVALUATEUR", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDEVALUATEUR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDCOLLABORATEUR, "IDCOLLABORATEUR", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDCOLLABORATEUR", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDCOLLABORATEUR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATEEVALUATION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATEEVALUATION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATEEVALUATION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATENEXTEVALUATION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATENEXTEVALUATION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATENEXTEVALUATION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.APPRECIATION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.APPRECIATION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.APPRECIATION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.STATUT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.STATUT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.STATUT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/ProjetGestionEval/ProjetGestionEval/Views/Evaluation/Index.cshtml
@model IEnumerable<ProjetGestionEval.evaluation>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutStablePage1.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DATEEVALUATION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATENEXTEVALUATION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.APPRECIATION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.STATUT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.collaborateur.NOM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.collaborateur1.NOM)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DATEEVALUATION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DATENEXTEVALUATION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.APPRECIATION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.STATUT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.collaborateur.NOM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.collaborateur1.NOM)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDEVALUATION }) |
            @Html.ActionLink("Details", "Details", new { id=item.IDEVALUATION }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IDEVALUATION })
        </td>
    </tr>
}

</table>